import * as os from 'os';
import * as path from 'path';

export const FUNCTION_CONF_DEFAULT = {
  description: 'This is default function description by fc-deploy component',
  runtime: 'nodejs10',
  handler: 'index.handler',
  memorySize: 128,
  timeout: 3,
  caPort: 9000,
  instanceConcurrency: 1,
  instanceType: 'e1',
  codeUri: './',
};

export const SUPPORTED_REMOVE_ARGS = ['service', 'function', 'trigger'];
export const FC_BASE_CACHE_DIR = path.join(os.homedir(), '.s/cache/fc-base');
export const FC_CODE_CACHE_DIR = path.join(FC_BASE_CACHE_DIR, 'code');
export const FC_NAS_SERVICE_PREFIX = '_FC_NAS_';
export const DESCRIPTION = 'generated by fc-deploy component';
