import * as os from 'os';
import * as path from 'path';

export const FUNCTION_CONF_DEFAULT = {
  description: 'This is default function description by fc-deploy component',
  runtime: 'nodejs10',
  handler: 'index.handler',
  memorySize: 128,
  timeout: 3,
  caPort: 9000,
  instanceConcurrency: 1,
  instanceType: 'e1',
  codeUri: './',
};

export const SUPPORTED_REMOVE_ARGS = ['service', 'function', 'trigger', 'domain'];
export const FC_BASE_CACHE_DIR = path.join(os.homedir(), '.s/cache/fc-base');
export const FC_CODE_CACHE_DIR = path.join(FC_BASE_CACHE_DIR, 'code');
export const FC_NAS_SERVICE_PREFIX = '_FC_NAS_';
export const DESCRIPTION = 'generated by fc-deploy component';

export const COMPONENT_HELP_INFO = [
  {
    header: 'fc-deploy component',
    content: 'You can use the component to deploy/remove your alicloud function computer resources.',
  },
  {
    header: 'Synopsis',
    content: '$ s <command> <options>',
  },
  {
    header: 'Command List',
    content: [
      { name: 'help', summary: 'Display help information.' },
      { name: 'deploy', summary: 'Deploy alicloud function computer resources.' },
      { name: 'remove', summary: 'Remove alicloud function computer resources.' },
    ],
  },
  {
    header: 'Global Options',
    optionList: [
      {
        name: 'assume-yes',
        description: 'Assume that the answer to any question which would be asked is yes.',
        alias: 'y',
        type: Boolean,
      },
      {
        name: 'help',
        description: 'Display help for command.',
        alias: 'h',
        type: Boolean,
      },
    ],
  },
  {
    header: 'Examples',
    content: [
      '$ s {bold deploy} {bold --help}',
      '$ s {bold deploy} {bold --assume-yes}',
      '$ s {bold remove} {underline service} ',
      '$ s {bold help}',
    ],
  },
];

export const DEPLOY_HELP_INFO = [
  {
    header: 'Deploy resources',
    content: 'Deploy resources',
  },
  {
    header: 'Usage',
    content: '$ s deploy <options>',
  },
  {
    header: 'Options',
    optionList: [
      {
        name: 'use-remote',
        description: 'Deploy resource using remote config.',
        type: Boolean,
      },
      {
        name: 'use-local',
        description: 'Deploy resource using local config.',
        type: Boolean,
      },
    ],
  },
  {
    header: 'Global Options',
    optionList: [
      {
        name: 'assume-yes',
        description: 'Assume that the answer to any question which would be asked is yes.',
        alias: 'y',
        type: Boolean,
      },
      {
        name: 'help',
        description: 'Display help for command.',
        alias: 'h',
        type: Boolean,
      },
    ],
  },
  {
    header: 'Examples',
    content: [
      '$ s {bold deploy} {underline --use-remote}',
    ],
  },
];

export const REMOVE_HELP_INFO = [
  {
    header: 'Remove resources',
    content: 'Specify RESOURCE to remove it and resource belonging to it.\n' +
'If {bold service} is specified, service and its functions should be removed.\n' +
'If {bold function} is specified, function and its triggers should be removed.\n' +
'If {bold trigger} is specified, you can specify the trigger name to remove the specific trigger or remove all triggers without trigger name.\n' +
'If {bold domain} is specified, you can specify the domain name to remove the specific domain or remove all domains without domain name.',
  },
  {
    header: 'Usage',
    content: '$ s remove <RESOURCE> <options>',
  },
  {
    header: 'Options',
    optionList: [
      {
        name: 'name',
        description: 'Resource name to be removed, only for trigger/domain resource.',
        alias: '-n',
        type: String,
      },
    ],
  },
  {
    header: 'Global Options',
    optionList: [
      {
        name: 'assume-yes',
        description: 'Assume that the answer to any question which would be asked is yes.',
        alias: 'y',
        type: Boolean,
      },
      {
        name: 'help',
        description: 'Help for rm.',
        alias: 'h',
        type: Boolean,
      },
    ],
  },
  {
    header: 'Examples',
    content: [
      '$ s {bold remove} {underline service}',
      '$ s {bold remove} {underline function}',
      '$ s {bold remove} {underline trigger} [{bold --name} {underline name}]',
      '$ s {bold remove} {underline domain} [{bold --name} {underline name}]',
    ],
  },
];
