edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: fcDeployApp       #  项目名称
access: default  #  秘钥别名

services:
  fc-deploy-test: #  服务名称
    component: ${path(../..)}  # 组件名称
    props: #  组件的属性值
      region: cn-hangzhou
      service:
        name: fc-deploy-service
        description: 'demo for fc-deploy component'
        internetAccess: true
        role:
          name: fc-deploy-role
          policies:
            - AliyunContainerRegistryReadOnlyAccess
      function:
        name: custom-container-function
        runtime: custom-container
        caPort: 8080
        codeUri: ./
        timeout: 60
        customContainerConfig:
          # image: ${env(image)}
          image: registry.cn-hangzhou.aliyuncs.com/shl-test/express:v5
          command: '["node"]'
          args: '["server.js"]'
        environmentVariables:
          testEnv: true
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: fc-deploy-service
              functionName: custom-container-function
