import * as core from '@serverless-devs/core';
import { SlsComponent } from '../component/sls';
import { replaceProjectName } from '../profile';
import { AlicloudClient } from './client';
import * as _ from 'lodash';

export interface LogConfig {
  project: string;
  logstore: string;
}


export class AlicloudSls extends AlicloudClient {
  async createDefaultSls(fcServiceName: string): Promise<any> {
    const defaultProject = _.toLower(`${this.credentials.AccountID}-${this.region}-logproject`);
    const defaultLogstore = _.toLower(`fc-service-${fcServiceName}-logstore`);
    const defaultDescription = 'Generated by alibaba fc-deploy component';
    const profileOfSls = replaceProjectName(this.serverlessProfile, `${this.serverlessProfile?.project.projectName}-sls-project`);

    const slsComponent = new SlsComponent(profileOfSls, defaultProject, defaultLogstore, this.region, this.credentials, this.curPath, undefined, defaultDescription);
    const slsComponentInputs = slsComponent.genComponentInputs('sls');
    const slsComponentIns = await core.load('devsapp/sls');
    await slsComponentIns.create(slsComponentInputs);
    return {
      project: defaultProject,
      logstore: defaultLogstore,
    };
  }
}
