import * as core from '@serverless-devs/core';
import { SlsComponent } from '../component/sls';
import { replaceProjectName } from '../profile';
import { AlicloudClient } from './client';

export interface LogConfig {
  project: string;
  logstore: string;
}


export class AlicloudSls extends AlicloudClient {
  async createDefaultSls(fcServiceName: string): Promise<any> {
    const defaultProject = `fc-deploy-component-generated-project-${this.region}`;
    const defaultLogstore = `fc-service-${fcServiceName}-logstore`;
    const defaultDescription = 'Generated by alibaba fc-deploy component';
    const profileOfSls = replaceProjectName(this.serverlessProfile, `${this.serverlessProfile?.project.projectName}-sls-project`);

    const slsComponent = new SlsComponent(profileOfSls, defaultProject, defaultLogstore, this.region, this.credentials, this.curPath, undefined, defaultDescription);
    const slsComponentInputs = slsComponent.genComponentInputs('sls');
    const slsComponentIns = await core.load('alicloud-sls');
    return await slsComponentIns.create(slsComponentInputs);
  }
}
